config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :flowers
  resources :compositions do
    resources :proportions
  end
  resources :orders do
    resources :quantities
    collection do
      get 'show_by_date'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/composition.rb
class Composition < ApplicationRecord
  has_many :proportions, dependent: :destroy
  has_many :quantities, dependent: :destroy
  has_many :flowers, through: :proportions

  validates :name, presence: true, uniqueness: true
  accepts_nested_attributes_for :quantities
end

app/models/flower.rb
class Flower < ApplicationRecord
  has_many :proportions, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :quantities, dependent: :destroy
  has_many :compositions, through: :quantities
  has_many :flowers, through: :compositions
  serialize :theme, Array
  validates :date, presence: true
end

app/models/proportion.rb
class Proportion < ApplicationRecord
  belongs_to :flower
  belongs_to :composition

  validates :stems_number, presence: true
  validates_uniqueness_of :composition, scope: :flower
end

app/models/quantity.rb
class Quantity < ApplicationRecord
  belongs_to :order
  belongs_to :composition

  validates :compositions_number, presence: true
  validates_uniqueness_of :order, scope: :composition
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
  before_action :set_composition, only: [:show, :edit, :update, :destroy]


  def index
    @compositions = Composition.all
  end

  def show
    @proportion = Proportion.new
  end

  def new
    @composition = Composition.new
  end

  def create
    @composition = Composition.new(params_composition)
    @order = Order.find(params[:order])
    @composition.name = "#{@composition.model} #{@order.name}"
    @composition.quantities[0].compositions_number = params[:composition][:quantities_attributes]["0"][:compositions_number].to_i
    @composition.quantities[0].order = @order
    @composition.quantities[0].composition = @composition
    if @composition.save
      redirect_to composition_path(@composition)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @composition.update(params_composition)
      redirect_to compositions_path
    else
      render :edit
    end
  end

  def destroy
    @composition.destroy
    redirect_to compositions_path
  end

  private

  def set_composition
    @composition = Composition.find(params[:id])
  end

  def params_composition
    params.require(:composition).permit(:name, :model, quantities_attributes: [compositions_number: []])
  end

end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_action :set_flower, only: [:show, :edit, :update, :destroy]

  def index
    @flowers = Flower.all
  end

  def show
  end

  def new
    @flower = Flower.new
  end

  def create
    @flower = Flower.new(params_flower)
    if @flower.save
      redirect_to flowers_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @flower.update(params_flower)
      redirect_to flowers_path
    else
      render :edit
    end
  end

  def destroy
    @flower.destroy
    redirect_to flowers_path
  end

  private

  def set_flower
    @flower = Flower.find(params[:id])
  end

  def params_flower
    params.require(:flower).permit(:name, :color, :photo)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :init_cmd, only: [:show, :show_by_date]

  def index
    @orders = Order.where("user_id = ?", current_user)
  end

  def show
    @composition = Composition.new
    @composition.quantities.build
    @cmd_detail = {}
    calcul_quantity
  end

  def show_by_date
    @orders = Order.where("user_id = ? AND date = ?", current_user, params[:format])
    @orders.each do |order|
      @cmd_detail = {}
      @order = order
      calcul_quantity
    end
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params_order)
    @order.user = current_user
    @order.theme = @order.theme.map { |id| id.to_i }
    if @order.save
      redirect_to order_path(@order)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @order.update(params_order)
      redirect_to orders_path
    else
      render :edit
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_path
  end

  private

  def init_cmd
    @cmd_gal = {}
    @group = {}
  end

  def calcul_quantity
    @order.quantities.each do |quantity|
      quantity.composition.flowers.each do |flower|
        nb = 0
        label = "#{flower.name} #{flower.color}"
        prop = flower.proportions.find_by(composition_id: quantity.composition.id).stems_number
        nb += prop * quantity.compositions_number
        if @cmd_gal.key?(label)
          @cmd_gal[label] += nb
        else
          @cmd_gal[label] = nb
        end
        if @cmd_detail.key?(label)
          @cmd_detail[label] += nb
        else
          @cmd_detail[label] = nb
        end
      end
    end
    @group[@order.name] = @cmd_detail
  end

  def set_order
    @order = Order.find(params[:id])
  end

  def params_order
    params.require(:order).permit(:date, :name, :theme => [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/proportions_controller.rb
class ProportionsController < ApplicationController

  def create
      @proportion = Proportion.new(params_proportion)
      @composition = Composition.find(params[:composition_id])
      @proportion.composition = @composition
      @proportion.save
      redirect_to composition_path(@composition)
  end

  def destroy
    @proportion = Proportion.find(params[:id])
    @proportion.destroy
    redirect_to composition_path(@proportion.composition_id)
  end

private
  def params_proportion
    params.require(:proportion).permit(:stems_number, :flower_id)
  end

end

app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController

  def create
      @quantity = Quantity.new(params_quantity)
      @order = Order.find(params[:order_id])
      @quantity.order = @order
      @quantity.save
      redirect_to order_path(@order)
  end


  def destroy
    @quantity = Quantity.find(params[:id])
    @quantity.destroy
    redirect_to order_path(@quantity.order_id)
  end

private

  def params_quantity
    params.require(:quantity).permit(:compositions_number, :composition_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/compositions/edit.html.erb
<%= render 'shared/form', thing: @composition %>

app/views/compositions/index.html.erb
<h1>Liste des compositions</h1>

<ol>
  <% @compositions.each do |composition| %>
  <li>
    nom : <%= link_to composition.name, composition_path(composition) %>
    <%= link_to edit_composition_path(composition), class: "delete-link hidden" do %>
      <button id="edit-btn" class="btn btn-tag"><i class="far fa-edit"></i></button>
    <% end %>
    <%= link_to composition_path(composition), method: 'DELETE', data: {confirm: "Are you sure?"}, class: "delete-link hidden" do %>
      <button id="delete-btn" class="btn btn-tag"><i class="far fa-times-circle"></i></button>
    <% end %>
      composition :
      <ul>
        <% composition.proportions.each do |compo| %>
        <li>
          <%= pluralize(compo.stems_number, 'tige') %> de <%= compo.flower.name %> <%= compo.flower.color %> <%= cl_image_tag compo.flower.photo.key, class: "avatar" %>
        </li>
        <% end %>
      </ul>
  </li>
  <% end %>
</ol>

<%= link_to 'ajouter une composition', new_composition_path %> <br>

app/views/compositions/new.html.erb
<%= render 'shared/form', thing: @composition %>

app/views/compositions/show.html.erb
<%= link_to compositions_path do %>
  <button  id="back" class="btn btn-success">Back...</button>
<% end %>


<h1><%= @composition.name %></h1>
<h6>Ajouter des fleurs</h6>
<p>
<%= simple_form_for [@composition, @proportion] do |f| %>
<% @flowers = Flower.where(id: @composition.quantities.first.order.theme) %>
<%= f.association :flower, as: :radio_buttons, collection: @flowers, label_method: lambda { |flower| cl_image_tag flower.photo.key, class: "avatar-large" }, wrapper: :vertical_collection_inline, value_method: :id, include_blank: false %>
<%= f.input :stems_number, label: "combien de tiges ?" %>
<%= f.submit "Ajouter flowers", class: "btn btn-success" %>
<% end %>
</p>
    <p>
    <ul>
      <% @composition.proportions.each do |compo| %>
      <li>
        <%= pluralize(compo.stems_number, 'tige') %> de <%= compo.flower.name %> <%= compo.flower.color %>
        <%= link_to composition_proportion_path(@composition, compo.id), method: 'DELETE', data: {confirm: "Are you sure?"}, class: "delete-link hidden" do %>
          <button id="delete-btn" class="btn btn-tag"><i class="far fa-times-circle"></i></button>
        <% end %>
      </li>
      <% end %>
    </ul>
    </p>


<%= link_to order_path(@composition.quantities.first.order) do %>
  <button  id="compo_complete" class="btn btn-primary">composition complète</button>
<% end %>

app/views/flowers/edit.html.erb
<%= render 'shared/form', thing: @flower %>

app/views/flowers/index.html.erb
<h1>Liste des fleurs</h1>
<%= link_to 'ajouter une fleur', new_flower_path %> <br>
<div class="card_container">
  <div class="cards d-flex flex-wrap">
    <% @flowers.each do |flower| %>
    <div class="card card-flower" style="width: 120px; height: 120px">
        <%= link_to flower_path(flower) do %>
          <%= cl_image_tag flower.photo.key, class: "card-img-top" %>
        <% end %>
      <div class="card-text overlay_fl">
        <%= flower.name %> <%= flower.color %>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flowers/new.html.erb
<%= render 'shared/form', thing: @flower %>

app/views/flowers/show.html.erb
<h2>Détails de <%= @flower.name %></h2>

<%= cl_image_tag @flower.photo.key %> - <%= @flower.name %>-<%= @flower.color %>
        <%= link_to edit_flower_path(@flower), class: "delete-link hidden" do %>
          <button id="edit-btn" class="btn btn-tag"><i class="far fa-edit"></i></button>
        <% end %>
        <%= link_to flower_path(@flower), method: 'DELETE', data: {confirm: "Are you sure?"}, class: "delete-link hidden" do %>
          <button id="delete-btn" class="btn btn-tag"><i class="far fa-times-circle"></i></button>
        <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/flashes' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/orders/edit.html.erb
<%= render 'shared/form', thing: @order %>

app/views/orders/index.html.erb
<h1>Liste des commandes</h1>

<ol>
  <% @orders.each do |order| %>
  <li>
    Commande <%= link_to order.name, order_path(order) %> du : <%= link_to order.date, show_by_date_orders_path(order.date) %>
    theme :
      <% order.theme.each do |id| %>
        <% @flower = Flower.find(id) %>
        <%= @flower.name %><%= cl_image_tag @flower.photo.key, class: "avatar" %>
      <% end %>
    <%= link_to edit_order_path(order), class: "delete-link hidden" do %>
      <button id="edit-btn" class="btn btn-tag"><i class="far fa-edit"></i></button>
    <% end %>
    <%= link_to order_path(order), method: 'DELETE', data: {confirm: "Are you sure?"}, class: "delete-link hidden" do %>
      <button id="delete-btn" class="btn btn-tag"><i class="far fa-times-circle"></i></button>
    <% end %>
    <br>
      comprenant :
      <ul>
        <% order.quantities.each do |item| %>
          <li>
            <% t = item.composition.name.split %>
            <% first_word = t.shift %>
            <% rest_sentence = t.join(" ") %>
            <%= pluralize(item.compositions_number, first_word) %> <%= rest_sentence %>
          </li>
      <% end %>
      </ul>
  </li>
  <% end %>
</ol>

<%= link_to 'ajouter une commande', new_order_path %> <br>

app/views/orders/new.html.erb
  <%= simple_form_for(@order)  do |f| %>
      <%= f.input :name %>
      <%= f.input :date, html5: true %>
      <%= f.input :theme,
      as: :check_boxes,
      collection: Flower.order(:color),
      label_method: lambda { |flower| "#{cl_image_tag flower.photo.key , class: "fl_label" }<br> #{flower.name} #{flower.color}".html_safe},
      wrapper: :vertical_collection_inline,
      include_hidden: false %>
      <%= f.submit %>
  <% end %>

app/views/orders/show.html.erb
<h2>Commande <%= @order.name %></h2>
<h6>pour le <%= @order.date %> :</h6>


<h4>Ajouter des Compositions</h4>
<p>
<%= simple_form_for @composition do |f| %>
<%= f.input :model %>
<%= hidden_field_tag :order, params[:id] %>
<%= f.simple_fields_for :quantities do |q| %>
<%= q.input :compositions_number, label: "quelle quantitée ?" %>
<% end %>
<%= f.submit "Ajouter les compositions", class: "btn btn-success" %>
<% end %>
</p>

<p>
<ul>
<% @order.quantities.each do |item| %>
  <li>
    <% t = item.composition.name.split %>
    <% first_word = t.shift %>
    <% rest_sentence = t.join(" ") %>
    <%= pluralize(item.compositions_number, first_word) %> <%= rest_sentence %>
    <%= link_to order_quantity_path(@order, item.id), method: 'DELETE', data: {confirm: "Are you sure?"}, class: "delete-link hidden" do %>
      <button id="delete-btn" class="btn btn-tag"><i class="far fa-times-circle"></i></button>
    <% end %>
  </li>
<% end %>
</ul>
</p>


soit les quantités de fleurs suivantes :
<p>
  <ul>
  <% @cmd_gal.each do |key, value|%>
    <li>
        <%= pluralize(value, 'tige') %> de <%= key %>
    </li>
    <% end %>
  </ul>
</p>


<%= link_to show_by_date_orders_path(@order.date) do %>
  <button class="btn btn-primary">commande complète</button>
<% end %>

app/views/orders/show_by_date.html.erb
<%= link_to orders_path do %>
  <button  id="back" class="btn btn-success">Back...</button>
<% end %>

pour le <%= @orders.first.date %> :<br>
Nous avons les commandes suivantes:
<% @orders.each do |order| %>
  <%= order.name %> ,
<% end %>
<br>soit les quantités suivantes :
<p>
  <ul>
  <% @cmd_gal.each do |key, value|%>
    <li>
      <%= pluralize(value, 'tige') %> de <%= key %>
        <% if  @group.count > 1 %>
          <ul>
            <% @group.each do |k,v| %>
              <% if @group.dig(k, key) %>
                <li>
                <%= @group.dig(k, key) %> pour <%= k %>
                </li>
              <% end %>
            <% end %>
          </ul>
        <% end %>
    </li>
    <% end %>
  </ul>
</p>

app/views/pages/home.html.erb
<h1>Aide à la commande de fleurs</h1>
<p>selectionne un item</p>

<%= link_to 'liste des fleurs', flowers_path %> <br>
<%= link_to 'ajouter une fleur', new_flower_path %> <br>

<%= link_to 'liste des compositions', compositions_path %> <br>
<%= link_to 'ajouter une composition', new_composition_path %> <br>

<%= link_to 'liste des commandes', orders_path %> <br>
<%= link_to 'ajouter une commande', new_order_path %> <br>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
  <%= simple_form_for(thing)  do |f| %>
      <%= f.input :name %>
      <%= f.input :color if thing == @flower %>
      <%= f.input :photo, as: :file if thing == @flower %>
      <%= f.input :date, html5: true if thing == @order %>
      <%= f.input :theme, as: :check_boxes, collection: Flower.order(:name), label_method: lambda { |flower| cl_image_tag flower.photo.key, class: "avatar-large" }, wrapper: :vertical_collection_inline, include_hidden: false if thing == @order %>
      <%= f.submit %>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://www.marie-myrtille.com/templates/yootheme/cache/monogramme_mm-ac3d2f3f.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Accueil", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Commandes", orders_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Compositions", compositions_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
          <%= link_to "fleurs", flowers_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/mikatoomik", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Profil", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
       <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>